name: Deploy Sphinx documentation to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust this to the branch you want to trigger the deployment from

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Replace with your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx-rtd-theme  # Replace with your required dependencies

      - name: Build documentation
        run: |
          cd docs
          make html  # Replace with your build command if different

      - name: Deploy to GitHub Pages
        run: |
          cd docs/build/html
          git init
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m "Deploy Sphinx documentation to GitHub Pages"
          git push --force --quiet "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}" master:gh-pages
